services:
  vinkvfxls:
    image: ghcr.io/vinkvfx/vinkvfxls:latest
    restart: unless-stopped
    ports:
      - "5082:5082" # Used for serving licenses
      - "5083:5083" # Optional for API requests
    environment:
      - VINKVFXLS_LICENSES="BD2204E2-971F-4FA3-9729-6109C0749923" # For single licenses
      - ACCEPT_EULA=true
    #   - VINKVFXLS_LICENSES="BD2204E2-971F-4FA3-9729-6109C0749923;6652D1B6-D111-4F90-A6A5-C45BF160043D" For multiple licenses
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5083/v1/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
